map cmd+n launch --type=tab --tab-title=nvim fish -l -c nvim
map kitty_mod+n launch --type=tab --tab-title=nvim fish -l -c nvim
map cmd+e launch --type=tab --tab-title=yazi fish -l -c yazi
map cmd+, new_tab
map kitty_mod+right next_window
map kitty_mod+left previous_window
